imgix/gatsby

- packages/gatsby-source-url/src/createImgixFluidFieldConfig.ts
- packages/gatsby-source-url/src/objectBuilders.ts
- packages/gatsby-source-url/test/createResolvers.test.ts
- packages/gatsby-source-url/test/utils/getSrcsetWidths.ts
```
{
imgixImage(url: ...) {
fluid(srcSetBreakpoints: [100, 200]) {
srcset // image.jpg?w=100 100w, .../image.jpg?w=200 200w
}
}
}
```
> feat(gatsby-source-url): allow developer to control srcset widths generated with args.srcSetBreakpoints

- packages/dev-and-e2e-test-environment/cypress/e2e/gatsby-source-url.js
- packages/dev-and-e2e-test-environment/src/pages/e2e/gatsby-source-url.tsx
- packages/gatsby-source-url/fragments.js
- packages/gatsby-source-url/package.json
- packages/gatsby-source-url/src/createImgixFixedFieldConfig.ts
- packages/gatsby-source-url/src/createImgixFluidFieldConfig.ts
- packages/gatsby-source-url/src/createRootImgixImageType.ts
- packages/gatsby-source-url/src/graphqlTypes.ts
- packages/gatsby-source-url/src/objectBuilders.ts
- packages/gatsby-source-url/src/publicTypes.ts
- packages/gatsby-source-url/src/utils.ts
- packages/gatsby-source-url/test/createResolvers.test.ts
- yarn.lock
```graphql
{
testImage: imgixImage(url: "/blog/unsplash-kiss.jpg") {
fixed(width: 100) {
...GatsbySourceImgixFixed
}
}
}
```
now works
> feat(gatsby-source-url): basic fixed field and tests

- packages/gatsby-source-url/README.md
- packages/gatsby-source-url/src/common/ioTs.ts
- packages/gatsby-source-url/src/common/tsUtils.ts
- packages/gatsby-source-url/src/gatsby-node.ts
- packages/gatsby-source-url/src/publicTypes.ts
- packages/gatsby-source-url/test/createResolvers.test.ts
```js
// gatsby-config.js
module.exports = {
//...
plugins: [
// your other plugins here
{
resolve: `@imgix/gatsby-source-url`,
options: {
domain: '<your imgix domain, e.g. acme.imgix.net>',
disableIxlibParam: true, // <-- set this to true
},
},
],
};
```
> feat(gatsby-source-url): disableIxlibParam global setting

- CONTRIBUTING.md
- package.json
- packages/gatsby-source-url/README.md
- packages/gatsby-source-url/src/common/imgix-core-js-wrapper.ts
- packages/gatsby-source-url/src/common/ioTs.ts
- packages/gatsby-source-url/src/createRootImgixImageType.ts
- packages/gatsby-source-url/src/gatsby-node.ts
- packages/gatsby-source-url/src/publicTypes.ts
- packages/gatsby-source-url/test/createResolvers.test.ts
This PR enables web proxy sources to be used with the following config
1. Set the plugin config in `gatsby-config.js` to the following:
```js
module.exports = {
//...
plugins: [
// your other plugins here
{
resolve: `@imgix/gatsby-source-url`,
options: {
domain: '<your proxy source domain, e.g. my-proxy-source.imgix.net>',
secureURLToken: '...', // <-- now required, your "Token" from your source page
defaultImgixParams: ['auto', 'format'],
},
},
],
};
```
2. Pass a **fully-qualified URL** to the `url` parameter in the GraphQL API. For example, to render a fixed image, a page would look like this:
```jsx
import gql from 'graphql-tag';
import Img from 'gatsby-image';
export default ({ data }) => {
return <Img fixed={data.imgixImage.fixed} />;
};
export const query = gql`
{
imgixImage(url: …
```
> feat(gatsby-source-url): support web proxy sources

- README.md
~⚠️ This PR isn't intended to be merged!~ **Edit: I've reworked this to live on in the main repo so it's easier to find.**
The idea of this PR is just to review this branch, which I will use to do an NPM release to `@imgix/gatsby-transform-url` to mark it as deprecated in favour of the main repo/package.
The command I will use to deprecate this library is:
```sh
npm deprecate @imgix/gatsby-transform-url "functionality moved to another package: @imgix/gatsby. See upgrade instructions at https://github.com/imgix/gatsby/<sha1>/gatsby-transform-url/README.md#deprecation-notice"
```
This will be updated when the API of `@imgix/gatsby` is finalised.
> docs: v1 upgrade information

- README.md
Updated [README](https://github.com/imgix/gatsby/blob/luis/drupalSource/README.md) to include gatsby-source-drupal configuration.
> docs(readme): add gastby-source-drupal config

- README.md
There is a code block under the [Adding a fields item correctly](https://docs.imgix.com/libraries/gatsby#adding-a-fields-item-correctly) section that is displaying as multiple inline blocks on docs.imgix.com. There is a possibility that the markdown parser expects a language declaration here, so adding one should fix this.
> docs: fix typo and code block

- .renovaterc.json
- package.json
This PR pulls in the renovate config from imgix/renovate-config and also updates semantic release to be compatible with this config
> config: update semantic release

- src/modules/gatsby-transform-node/gatsby-node.ts
- src/modules/gatsby-transform-url/index.ts
- test/unit/source-url/source-url.test.ts
- test/unit/transform-url/transform-url.test.ts
This is so that our internal analytics can actually pick up this ixlib. This wasn't working before since our internal spec can only handle one dash.
> fix: use camelCased ixlib param

- src/modules/gatsby-source-url/createImgixGatsbyImageDataFieldConfig.ts
- test/unit/source-url/source-url.test.ts
Our helper to help untransform parameters like `fpZ` into `fp-z` wasn't being used for `gatsbyImageData`. This PR fixes that.
Fixes #115
> fix(gatsby-image-data): untransform imgix params to fix dash imgix params

- package.json
This PR fixes two issues:
1. Apostrophes don't render correctly on the Gatsby website, so this PR doesn't use apostrophes anymore
2. Added the word "official" to give us more credibility
> docs: update npm description

- src/modules/gatsby-plugin/buildGatsbyImageDataBaseArgs.ts
- test/unit/source-url/source-url.test.ts
This PR allows the `gatsbyImageData` field to override `w` and `h` parameters provided by users via the `imgixParams` field argument.
This is necessary to ensure data returned by the field is responsive. In `gatsbyImageData` fields, `w` and `h` parameters do not make sense to prioritize.
This practice is already being done with `fixed` and `fluid` fields.
1. Query for `gatsbyImageData` with this argument: `imgixParams: { w: 2, h: 1}`.
Without this PR, all URLs in the generated srcSets will have `w=2&h=1`.
With this PR, `w` and `h` will be appropriately set for the srcSet.
Related comment: https://github.com/imgix/gatsby/issues/122#issuecomment-846256825
> fix: override w and h params in gatsbyImageData

- src/common/uri.ts
- test/unit/transform-url/transform-url.test.ts
Fixes bug identified in #122 where URLs that had a `?` were being truncated. This is incorrect behaviour since we encode `?` as a special parameter and it should not be removed.
> test: don't truncate url at ?

- test/unit/transform-url/transform-url.test.ts
🚨 **NB: this is a stacked PR, so only review [this changeset](https://github.com/imgix/gatsby/pull/128/files/95f82b16d64b08a54b57961db5a3e749a396fc21..c8b2106da28e3b4919a9d2343a1be1edfcf5ebfd), not the full PR**
This function wasn't tested before, so we added a basic test and also a test for the `?` truncation.
> test: add tests for getGatsbyImageData

- src/modules/gatsby-plugin/gatsby-node.ts
This commit addresses issue #136. 
When extending a type, the plugin can at times fail to determine the original type extended the `Node` interface. This is likely a race condition, where the node we're extending is being created by `buildObjectType` before it's declared to be implementing the Node interface.
This means that our plugin could cause errors to be thrown at build time, as the newly created type was expected to be of type `Node`.
For more information see the Gatsby documentation here:
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/#gatsby-type-builders
> "When defining top-level types, don't forget to pass `interfaces: ['Node']`, which does the same for Type Builders as adding `implements Node` to SDL-defined types."
Related issue: #136 
Code: …
> fix(pe1168): looks like node but missing interface

- src/modules/gatsby-plugin/createImgixGatsbyImageDataFieldConfig.ts
This PR fixes a bug causing `createImgixGatsbyImageDataFieldConfig` to crash when using Gatsby 4 with Deferred Static Generation or Server-Side Rendering.
It uses a namespace import for Ramda rather than a default import. A namespace import was already being used for all other Ramda usage throughout the library.
The following error appears after running `gatsby serve` without the PR:
```
[nix-shell:~/projects/tmp/gatsby-4-prismic-demo]$ yarn serve
yarn run v1.22.10
$ gatsby serve
ERROR #11321  PLUGIN
"gatsby-source-prismic" threw an error while running the createSchemaCustomization lifecycle:
Cannot read property 'pick' of undefined
TypeError: Cannot read property 'pick' of undefined
- index.js:296774 Object.createImgixGatsbyImageFieldConfig …
```
> fix: use namespace import for Ramda

- src/common/uri.ts
This PR fixes the `parsePath` function to support URLs containing a hash symbol. For example, a URL that looks like this:
```
https://example.net/image-#1.png
```
Without this fix, the plugin will strip everything after `#`, resulting in something like the following:
```
https://example.net/image-?ixlib=gatsbyFP
```
> fix: support URLs with hash symbol

- README.md
Addresses confusion in #142, making it super clear that Web Proxy Sources are not supported with the URL transform API
> docs: add note about web proxy sources and URL transform API

- package.json
Updates project peer dependencies to include version ^2 of gatsby-plugin-image. Verified compatibility in https://github.com/sherwinski/gatsby-v4-imgix-demo
> chore: update gatsby-plugin-image peer dependency

- src/common/ar.ts
- src/modules/gatsby-plugin/createImgixGatsbyImageDataFieldConfig.ts
- src/modules/gatsby-plugin/createImgixUrlFieldConfig.ts
- src/modules/gatsby-plugin/gatsby-node.ts
- src/modules/gatsby-plugin/objectBuilders.ts
- src/modules/gatsby-transform-url/gatsbyPluginImageComponent.tsx
- src/publicTypes.ts
- test/common/getSrcsetWidths.ts
- test/dev-and-e2e/gatsby-config.js
This PR fixes an error thrown when building sites using Gatsby 4 by only using Ramda with named imports. See this issue: https://github.com/prismicio/prismic-gatsby/issues/488
I have recreated the issue by using Gatsby 4's [Deferred Static Generation](https://www.gatsbyjs.com/docs/how-to/rendering-options/using-deferred-static-generation/) feature. The linked issue reports that the error is also thrown in non-DSG sites, however.
It appears to be an issue in the way Gatsby bundles code for its standalone GraphQL query server. The Ramda `*` import seems to use the `default` export after bundling. I don't know why this happens, but changing to named imports circumvents the issue.
> fix: "cannot read properties of undefined (reading 'pick')" error

- README.md
- package.json
- src/modules/gatsby-plugin/gatsby-node.ts
- src/publicTypes.ts
- test/dev-and-e2e/gatsby-config.js
- test/dev-and-e2e/gatsby-node.js
- test/unit/source-url/source-url.test.ts
- yarn.lock
This PR fixes #147. Before this PR, the URL was retrieved in the GraphQL from the underlying data with a function configuration option. This was incompatible with Gatsby v4 (specifically DSG and SSR pages), so the configuration was changed to be a simple string configuration, which was compatible. Furthermore, the name of the config option was changed to better match the new behaviour.
> feat!: update getURL config to use string

- package.json
- yarn.lock
This reverts commit 335362bf10e703b8865f9e722dde1c0f16a6affd because it broke the build
> chore(dev-deps): revert "update babel monorepo"

- CHANGELOG.md
- README.md
- package.json
- src/common/constants.ts
- src/modules/gatsby-plugin/gatsby-node.ts
- src/publicTypes.ts
- test/dev-and-e2e/gatsby-config.js
- test/dev-and-e2e/gatsby-node.js
- test/unit/source-url/source-url.test.ts
- yarn.lock
This will release the current changes below: 
* change getURL config from function to string
* change getURL config from function to string ([0844948](0844948))
> chore: release v2

- package.json
- test/dev-and-e2e/gatsby-config.js
- yarn.lock
This dependency was used by the new Gatsby v4 release, but not added as a dep
> chore: add lodash.get dependency

- src/api/fetchImgixMetadata.ts
- src/modules/gatsby-plugin/resolveDimensions.ts
> chore: refactor return type of fetchImgixMetadata

- src/common/utils.ts
> chore: remove unused fp-ts helpers

- src/gatsby-node.ts
- src/modules/gatsby-plugin/gatsby-node.ts
- src/modules/gatsby-plugin/pluginOptionsSchema.ts
- src/publicTypes.ts
From recommendation from Angelo, this should be used instead of doing our own type checking for the plugin options
> chore: use pluginOptionsSchema for options type checking

- src/common/imgix-js-core-wrapper.ts
- test/unit/source-url/source-url.test.ts
We were using `ImgixClient.settings` to attempt to set `includeLibraryParam` to `false`
We pass `includeLibraryParam` using `options` which correctly disables the ixlib param.
> fix(ixlib): correctly sets includeLibraryParam to false 

- .github/workflows/add-to-project.yml
This commit adds a GH action to automatically add opened issues with the bug or needs-triage tags to the SDK issues project board.
> chore: add issues gh action

- README.md
Adds additional detail to the `ixlib` section of the Gatsby documentation, clarifying the differences between `includeLibraryParam` and `disableIxlibParam`, as users has expressed confusion on this point.
> docs(ixlib): clarify disabling ixlib parameter

- package.json
Adds additional script to ensure properly updated `dist` prior to release.
Library is not guaranteed to execute a `build` step to properly update `dist` directory prior to deployment; as a result, some libraries include the prior release in their `dist` folder.
We include both a `prepare` and a `prepublishOnly` step to ensure that the library executes a build prior to deploying a release.
> ci(deploy): add prepare step

- src/modules/gatsby-plugin/pluginOptionsSchema.ts
- test/unit/pluginHelpers.test.ts
Fix regression where `domain` was set as required in the configuration options.
The `domain` configuration field was set as `required`.
`domain` can be set to an empty string, allowing absolute URLs to be used with the plugin.
> fix: set domain as optional

- package.json
This PR bumps `gatsby-plugin-image` version ranges to include v3. Fixes an installation issue with Gatsby v5, which requires version 3.
> fix(deps): update gatsby-plugin-image range

- CHANGELOG.md
- package.json
- src/common/constants.ts
Merge `next` into `main`
Closes: #266 
- [fix(deps): update gatsby-plugin-image range](https://github.com/imgix/gatsby/commit/fecccdf71f26298e809234d2cdc13f52a6bc54c9)
- [chore(release): 2.1.2-rc.1](https://github.com/imgix/gatsby/commit/d543df97923697cd135611cad9f2b170fa70e336)
> chore: merge next into main

- package.json
- src/modules/gatsby-plugin/graphqlTypes.ts
- yarn.lock
This PR ensures that `spec.short_description` is defined before it's accessed. There is the possibility a param does not include that property so we should not assume it is always defined.
This PR also bumps the `imgix-url-params` dependency version to the newest version.
Buils would break because the `short_name` prop was not defined when accessed.
Build succeeded, as we check that it's defined before accessing.
- Addresses https://github.com/imgix/gatsby/issues/270
> fix(graphql-types): ensure short-description is defined 
