.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/pull_request_template.md

chore: add issue and PR templates

---

.prettierrc.js
.travis.yml
README.md
jest.config.js
packages/gatsby-transform-url/test/index.test.ts
tsconfig.json

ci: add travis config

---

.travis.yml
package.json
packages/gatsby-transform-url/package.json
packages/gatsby-transform-url/tsconfig.json
tsconfig.json
yarn.lock

config: minimal build config

---

README.md
package.json
packages/dev-environment/package.json
packages/gatsby-transform-url/README.md
packages/gatsby-transform-url/package.json
packages/gatsby-transform-url/src/common/uri.ts
packages/gatsby-transform-url/src/index.ts
packages/gatsby-transform-url/src/types.ts
packages/gatsby-transform-url/test/index.test.ts
packages/gatsby-transform-url/tsconfig.json
yarn.lock

This PR represents all the foundational work to take gatsby-transform-url to v1

Main PR for gatsby-transform-url v1

---

README.md
packages/dev-environment/src/pages/using-typescript.tsx
packages/gatsby-transform-url/README.md
packages/gatsby-transform-url/src/index.ts
packages/gatsby-transform-url/src/types.ts

docs(gatsby-transform-url): improve docs

---

packages/gatsby-transform-url/README.md
packages/gatsby-transform-url/src/index.ts
packages/gatsby-transform-url/src/types.ts
packages/gatsby-transform-url/test/index.test.ts

ssia
NB: based on a PR branch. Change base before merging.

feat(gatsby-transform-url): generate webp urls

---

packages/gatsby-transform-url/README.md
packages/gatsby-transform-url/src/index.ts

docs(gatsby-transform-url): better information about ix params and auto params

---

packages/gatsby-source-url/package.json
packages/gatsby-source-url/tsconfig.json

config(gatsby-source-url): npm and typescript config

---

packages/gatsby-transform-url/LICENSE
packages/gatsby-transform-url/package.json

config(gatsby-transform-url): add license and keywords

---

packages/gatsby-source-url/src/createImgixFluidFieldConfig.ts
packages/gatsby-source-url/src/objectBuilders.ts
packages/gatsby-source-url/test/createResolvers.test.ts

These params will affect both the aspect ratio and the max sizes of both the src and srcsets

feat: handle maxWidth and maxHeight params correctly in fluid field

---

packages/gatsby-source-url/fragments.js
packages/gatsby-source-url/src/objectBuilders.ts
packages/gatsby-source-url/test/createResolvers.test.ts

feat(gatsby-source-url): explicitly set webp format for webp src and srcset

---

packages/gatsby-source-url/src/api/fetchBase64Image.ts
packages/gatsby-source-url/src/createImgixBase64FieldConfig.ts
packages/gatsby-source-url/src/createImgixFluidFieldConfig.ts
packages/gatsby-source-url/src/createRootImgixImageType.ts
packages/gatsby-source-url/src/graphqlTypes.ts
packages/gatsby-source-url/src/objectBuilders.ts
packages/gatsby-source-url/src/privateTypes.ts
packages/gatsby-source-url/test/createResolvers.test.ts

feat(gatsby-source-url): implement base64/LQIP image loading

---

packages/gatsby-source-url/README.md
packages/gatsby-source-url/src/createRootImgixImageType.ts

docs(gatsby-source-url): write initial docs

---

packages/gatsby-source-url/package.json
packages/gatsby-source-url/src/common/fpTsUtils.ts
packages/gatsby-source-url/src/createImgixFixedFieldConfig.ts
packages/gatsby-source-url/src/createImgixFluidFieldConfig.ts
packages/gatsby-source-url/src/createImgixUrlFieldConfig.ts
packages/gatsby-source-url/src/createRootImgixImageType.ts
packages/gatsby-source-url/src/gatsby-node.ts
packages/gatsby-source-url/src/objectBuilders.ts
packages/gatsby-source-url/src/publicTypes.ts
packages/gatsby-source-url/src/utils.ts
packages/gatsby-source-url/test/createResolvers.test.ts
yarn.lock

feat(gatsby-source-url): implement global default imgix parameters 

---

packages/gatsby-source-url/README.md
packages/gatsby-source-url/src/gatsby-node.ts
packages/gatsby-source-url/src/publicTypes.ts
packages/gatsby-source-url/test/createResolvers.test.ts

feat(gatsby-source-url): allow secure url tokens to be generated

---

.travis.yml
gatsby-browser.js
gatsby-node.js
gatsby-ssr.js
jest.config.js
lerna.json
package.json
test/gatsby-plugin.test.ts
tsconfig.json

config: semantic release and first steps towards single repo

---

.all-contributorsrc
README.md

I indented everything one level deeper and also moved the `` to fix display issues in the docs site.
I also snuck a little fix for the dependencies badge.

docs: fix display issues

---

README.md
src/modules/gatsby-source-url/createImgixFixedFieldConfig.ts
src/modules/gatsby-source-url/createImgixFluidFieldConfig.ts
src/modules/gatsby-source-url/createImgixUrlFieldConfig.ts
src/modules/gatsby-source-url/graphqlTypes.ts
test/unit/source-url/source-url.test.ts

Thanks so much for the help on this @luqven. I ended up going with a more straightforward solution instead of crafting a "nice" solution here.
Fixes #61

fix: imgix params with dash not working correctly, and correct types

---

package.json
src/modules/gatsby-source-url/createImgixFixedFieldConfig.ts
src/modules/gatsby-source-url/createImgixFluidFieldConfig.ts
src/modules/gatsby-source-url/createImgixGatsbyImageDataFieldConfig.ts
src/modules/gatsby-source-url/createImgixUrlFieldConfig.ts
src/modules/gatsby-source-url/graphqlTypes.ts
test/dev-and-e2e/package.json
test/dev-and-e2e/yarn.lock
yarn.lock

feat: add ix-params to gatsbyImageData

---

.gitignore
.vscode/settings.json

chore: remove vs code files

---

README.md

Use `./` so FE team can transform them

docs: fix image locations

---

package.json
yarn.lock

chore: add semantic release dep

---

src/modules/gatsby-source-url/createImgixGatsbyImageDataFieldConfig.ts

fix: remove a console.log that slipped through

---

src/modules/gatsby-transform-url/gatsbyPluginImage.ts
test/common/url.ts
test/dev-and-e2e/cypress/e2e/gatsby-transform-url.js
test/dev-and-e2e/src/pages/e2e/gatsby-transform-url.tsx
test/unit/gatsby-plugin-image-hook.test.ts

Some type changes sprinkled in here for good measure

test(hook): initial unit tests and some implementations

---

src/modules/gatsby-transform-url/gatsbyPluginImage.ts
test/common/url.ts
test/unit/gatsby-plugin-image-hook.test.ts

feat: more work on hook and component

---

README.md
src/common/utils.ts
src/modules/gatsby-source-url/createImgixFixedFieldConfig.ts
src/modules/gatsby-source-url/createImgixFluidFieldConfig.ts
src/modules/gatsby-source-url/createImgixGatsbyImageDataFieldConfig.ts
test/unit/source-url/source-url.test.ts

This PR handles some outstanding TODOs from the original library development.

chore: handle some todos and add placeholderImgixParams feature

---

.github/workflows/commitlint.yml

config: add commitlint as a GH action

---

README.md
src/modules/gatsby-source-url/createImgixGatsbyImageDataFieldConfig.ts
src/modules/gatsby-source-url/objectBuilders.ts
src/pluginHelpers.ts

Helpers for gatsby-source-prismic

feat: export object builders for third party plugins

---

src/modules/gatsby-source-url/createImgixUrlFieldConfig.ts
src/modules/gatsby-source-url/graphqlTypes.ts
src/modules/gatsby-transform-node/gatsby-node.ts
src/modules/gatsby-transform-url/gatsbyPluginImage.ts
test/dev-and-e2e/src/pages/e2e/gatsby-transform-node.tsx

chore: resolve some todos

---

README.md

docs: update readme to include type warning clarification

---

package.json

chore: fix chalk to v4 to fix build error

---

test/dev-and-e2e/gatsby-config.js

test: set e2e config correctly

---

.circleci/config.yml
CHANGELOG.md
package.json
src/common/constants.ts

This PR should fix #183 by building the project before running semantic release

fix: build before deploying

---

src/modules/gatsby-plugin/gatsby-node.ts

chore(fp-ts): refactor getFieldValue

---

src/modules/gatsby-plugin/gatsby-node.ts

chore(fp-ts): refactor decodeOptions

---

src/modules/gatsby-plugin/createImgixBase64FieldConfig.ts
src/modules/gatsby-plugin/gatsby-node.ts
src/publicTypes.ts

chore(fp-ts): first refactor of createImgixBase64FieldConfig

---

src/modules/gatsby-plugin/createImgixGatsbyImageDataFieldConfig.ts

chore(fp-ts): refactor resolveGatsbyImageData

---

src/api/fetchBase64Image.ts
src/modules/gatsby-plugin/createImgixBase64FieldConfig.ts
src/modules/gatsby-plugin/createImgixGatsbyImageDataFieldConfig.ts

chore(fp-ts): refactor fetchImgixBase64Image return type

---

src/api/fetchBase64Image.ts
src/modules/gatsby-plugin/createImgixGatsbyImageDataFieldConfig.ts

chore(fp-ts): refactor fetchImgixDominantColor return type

---

src/api/fetchBase64Image.ts

chore: add jsdoc to api functions

---

src/common/log.ts

chore: add log function and jsdoc

---

src/api/fetchBase64Image.ts
src/api/fetchImgixMetadata.ts
src/common/cache.ts

chore(fp-ts): refactor cache helpers

---

src/modules/gatsby-plugin/createImgixFixedFieldConfig.ts
src/modules/gatsby-plugin/createImgixFluidFieldConfig.ts
src/modules/gatsby-plugin/createImgixGatsbyImageDataFieldConfig.ts
src/modules/gatsby-plugin/resolveDimensions.ts

chore: refactor body of resolveDimensions

---

src/modules/gatsby-plugin/createImgixFixedFieldConfig.ts
src/modules/gatsby-plugin/createImgixFluidFieldConfig.ts
src/modules/gatsby-plugin/createImgixGatsbyImageDataFieldConfig.ts
src/modules/gatsby-plugin/resolveDimensions.ts

chore: refactor return type of resolveDimensions

---

src/modules/gatsby-plugin/createImgixFixedFieldConfig.ts
src/modules/gatsby-plugin/createImgixGatsbyImageDataFieldConfig.ts

chore(fp-ts): refactor createImgixFixedFieldConfig

---

package.json
src/common/ar.ts
src/modules/gatsby-transform-url/index.ts
yarn.lock

chore(fp-ts): refactor aspect ratio helpers

---

package.json
src/common/ar.ts
src/common/imgix-js-core-wrapper.ts
src/modules/gatsby-transform-url/index.ts
yarn.lock

chore(fp-ts): refactor imgix-js-core-wrapper

---

src/common/utils.ts

chore: remove unused helpers

---

src/modules/gatsby-plugin/createImgixFluidFieldConfig.ts

chore(fp-ts): refactor createImgixFluidFieldConfig

---

src/modules/gatsby-plugin/createImgixUrlFieldConfig.ts

chore(fp-ts): refactor createImgixUrlFieldConfig

---

src/modules/gatsby-plugin/createImgixGatsbyImageDataFieldConfig.ts

chore: add comment for createImgixGatsbyImageFieldConfig function

---

src/common/ar.ts
src/common/cache.ts
src/common/imgix-js-core-wrapper.ts
src/modules/gatsby-plugin/createImgixGatsbyImageDataFieldConfig.ts
src/modules/gatsby-plugin/gatsby-node.ts

This PR addresses comments from previous fp-ts refactor PRs

chore: PR comment follow-ups

---

CHANGELOG.md
package.json
src/common/constants.ts
src/common/imgix-js-core-wrapper.ts
test/unit/source-url/source-url.test.ts

fix: correctly set ixlib and add prePublish script

---

.github/workflows/add-to-project.yml

chore: add version number to gh action

---

package.json

ci: add prepare step

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/workflows/add-pr-to-project.yml

This PR updates the GH action and issue templates to remove references to vue and fix the add PR to project action title.

chore: update github actions and templates

---

.codesandbox/Dockerfile
.codesandbox/environmet.json
.codesandbox/tasks.json
test/dev-and-e2e/package.json

This PR adds a CodeSandbox config to make it easier for contributors to demonstrate changes in PRs.

chore: add codesandbox config

---

test/unit/pluginHelpers.test.ts

test(config): fix config test

---

README.md

docs(readme): update domain to be optional

---

.codesandbox/Dockerfile
.codesandbox/environmet.json
.codesandbox/tasks.json
CHANGELOG.md
README.md
package.json
src/common/constants.ts
src/modules/gatsby-plugin/pluginOptionsSchema.ts
test/dev-and-e2e/package.json
test/unit/pluginHelpers.test.ts

- Fix regression where the `domain` config option was set as required.
- Add `.codesandbox` configs for easier PR reviews
- Update `README.md` to reflect `domain` _is_ optional for non-web-proxy sources.
Closes: #254 
- `domain` Gatby config option was required, making it impossible to use absolute URLs.
- `domain` Gatsby config option is optional, allowing folks to use absolute URLs with the plugin.
- new unit test ensures there's no future regression
- go to [CodeSandbox](https://codesandbox.io/p/github/imgix/gatsby/next?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A4%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A4%7D%5D&workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSid …

fix: set domain as optional
